<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\EventSourcing\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="OpenTelemetry.Api" />
  </ItemGroup>

   <ItemGroup>
    <!-- O pacote Mediator.SourceGenerator deve ser referenciado no projeto que 
    usa os handlers para a geracao de codigo funcionar corretamente. -->
   <PackageReference Include="Mediator.Abstractions" />
   <PackageReference Include="MongoDB.Driver"/>
 </ItemGroup>


</Project>
