<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Abstractions\BuildingBlocks.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Core\BuildingBlocks.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Brands\ValueObjects\" />
    <Folder Include="Categories\" />
    <Folder Include="Suppliers\" />
    <Folder Include="Shared\" />
    <Folder Include="Product\" />
  </ItemGroup>

</Project>
